version: "3"

services:
  verdaccio:
    container_name: eraci-verdaccio
    image: verdaccio/verdaccio
    ports:
      - 34873:4873
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/htpasswd:/verdaccio/htpasswd
  redis:
    container_name: eraci-redis
    image: redis
    ports:
      - 36379:6379
  docker-registry:
    container_name: eraci-docker-registry
    image: registry:2
    ports:
      - 35000:5000
