name: Main

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

    steps:
      - uses: actions/checkout@v2

      - name: install k3d
        run: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: typescript-build-cache
        with:
          path: |
            **/dist
          key: typescript-build

      - uses: actions/cache@v2
        id: eslint-cache
        with:
          path: .eslintcache
          key: eslint-cache

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn Install
        run: yarn install --immutable
      - name: Typescript Build
        run: yarn build

      - name: Execute ERA CI
        env:
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          FULL_RUN: true
        run: |
          if [ "$CI_NODE_INDEX" -eq "0" ]
          then
            yarn run-era-ci
          else
            yarn run-task-worker
          fi
